DROP TABLE IF EXISTS Error;
DROP TABLE IF EXISTS Tags;
DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS Eventi;
DROP TABLE IF EXISTS Album;
DROP TABLE IF EXISTS Articoli;
DROP TABLE IF EXISTS Recensioni;
DROP TABLE IF EXISTS Gallerie;
DROP TABLE IF EXISTS Commenti;
DROP TABLE IF EXISTS Valutazioni;
DROP TABLE IF EXISTS Posts;
DROP TABLE IF EXISTS Foto;
DROP TABLE IF EXISTS Editori;
DROP TABLE IF EXISTS Utenti;
DROP TABLE IF EXISTS Account;












